model training will not run
ValueError: y should be a 1d array, got an array of shape () instead.

labels not being the right shape, maybe try labelEncoder instead of CountVectorizer